-- MySQL Script generated by MySQL Workbench
-- Wed Jul  6 12:35:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema organica_database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `organica_database` ;

-- -----------------------------------------------------
-- Schema organica_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `organica_database` DEFAULT CHARACTER SET utf8 ;
USE `organica_database` ;

-- -----------------------------------------------------
-- Table `organica_database`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organica_database`.`address` ;

CREATE TABLE IF NOT EXISTS `organica_database`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `province_city` VARCHAR(100) NOT NULL,
  `district` VARCHAR(100) NOT NULL,
  `town` VARCHAR(100) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_address_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `organica_database`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `organica_database`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organica_database`.`cart` ;

CREATE TABLE IF NOT EXISTS `organica_database`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `note` VARCHAR(200) NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_cart_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `organica_database`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `organica_database`.`cart_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organica_database`.`cart_has_product` ;

CREATE TABLE IF NOT EXISTS `organica_database`.`cart_has_product` (
  `cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`cart_id`, `product_id`),
  INDEX `fk_cart_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_cart_has_product_cart1_idx` (`cart_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_has_product_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `organica_database`.`cart` (`id`),
  CONSTRAINT `fk_cart_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `organica_database`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `organica_database`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organica_database`.`category` ;

CREATE TABLE IF NOT EXISTS `organica_database`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `group_table_id` INT NOT NULL,
  PRIMARY KEY (`id`, `group_table_id`),
  INDEX `fk_category_group_table1_idx` (`group_table_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_group_table1`
    FOREIGN KEY (`group_table_id`)
    REFERENCES `organica_database`.`group_table` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `organica_database`.`describe_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organica_database`.`describe_table` ;

CREATE TABLE IF NOT EXISTS `organica_database`.`describe_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(5000) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_describe_table_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_describe_table_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `organica_database`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `organica_database`.`group_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organica_database`.`group_table` ;

CREATE TABLE IF NOT EXISTS `organica_database`.`group_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `organica_database`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organica_database`.`image` ;

CREATE TABLE IF NOT EXISTS `organica_database`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source` VARCHAR(45) NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_image_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `organica_database`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `organica_database`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organica_database`.`order` ;

CREATE TABLE IF NOT EXISTS `organica_database`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cart_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cart_id`, `user_id`),
  INDEX `fk_order_cart1_idx` (`cart_id` ASC) VISIBLE,
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `organica_database`.`cart` (`id`),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `organica_database`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `organica_database`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organica_database`.`product` ;

CREATE TABLE IF NOT EXISTS `organica_database`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` INT NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `discount` INT NULL DEFAULT NULL,
  `quantity` INT NOT NULL,
  `quality` INT NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_product_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `organica_database`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `organica_database`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organica_database`.`role` ;

CREATE TABLE IF NOT EXISTS `organica_database`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `organica_database`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organica_database`.`user` ;

CREATE TABLE IF NOT EXISTS `organica_database`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `organica_database`.`user_has_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organica_database`.`user_has_role` ;

CREATE TABLE IF NOT EXISTS `organica_database`.`user_has_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_has_role_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_has_role_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `organica_database`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `organica_database`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
